### ISSUE TITLE
Wonder the meanings of dimensions of the mock inputs.

### ISSUE THREAD

**Issue by Taskii-Lei** [lucidrains/mmdit#3]
I want to know the meanings of various dimensions of mock inputs. Why is the second dimension of images tokens different from text tokens? 
```
# mock inputs
time_cond = torch.randn(2, 256)
text_tokens = torch.randn(2, 512, 768)
text_mask = torch.ones((2, 512)).bool()
image_tokens = torch.randn(2, 1024, 512)
```
Additionally, if I only use CLIP as the encoder, the image tokens and text tokens obtained are both two-dimensional data of [batchsize, out_dim]. Do I need to transform them into three-dimensional data? (For example, images tokens and text tokens could both be [1, 512]). If I change them to :
```
time_cond = torch.randn(1, 256)
text_tokens = torch.randn(1, 512)
text_mask = None
image_tokens = torch.randn(1, 512)
```
Is it reasonable or would it work ? Thank you very much to the author!

**Comment by lucidrains** [comment]
@Taskii-Lei hey Lei

yes, that's right, you'll want to rearrange the dimensions from `b c h w -> b (h w) c` in einops notation. spatial is flattened into the second dimension, last dimension for features

**Comment by Taskii-Lei** [comment]
Thank you so much!
